const RoutePath = {
  home: "",
  entry: "/entry",
  signIn: "/sign-in",
  signUp: "/sign-up",
  findPassword: "/find-password",
  resetPassword: "/reset-password",
  activeUser: "/active",
  communityHome: "/community/list/:category",
  communityNew: "/community/new",
  communityEdit: "/community/:communityId/edit",
  communityComment: "/community/:communityId/comments",
  communityDetail: "/community/:communityId",
  mypage: "/mypage/:tab",
  myProfile: "/mypage/profile",
  search: "/search",
  setting: "/setting",
  noticeList: "/setting/notice/list",
  noticeDetail: "/setting/notice/:noticeId",
  qnaList: "/setting/qna/list",
  qnaDetail: "/setting/qna/:qnaId",
  qnaForm: "/setting/qna/form",
  vocForm: "/setting/voc/form",
};

export default RoutePath;