name: Build CI
on:
  push:
    branches:
      - master
      - dev
      - release*

  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: npm

      - name: Install packages
        run: npm ci

      - name: Build Project
        run: npm run build
        env: 
          CI: false

      - name: Build Storybook
        run: npm run build-storybook
        env:
          CI: false
